### ISSUE TITLE
Crashes Aseprite at time.

### ISSUE THREAD

**Issue by natesturdevant** [CarbsCode/CarbsAsepriteExtensions#1]
This is not going to be particularly helpful I'm afraid but I've managed to crash Aseprite a couple of times now while trying to do some tweens.  Since I'm kinda dumb and I don't really know what I'm doing my usage of the Tween Machine is essentially to bang on it until it does what I want and some of what i want isn't even what this thing does.  Like, it would be great to add key frames and do tween animation but this is more for rotation and sizing and position.  Anyway, I was trying to move a sprite on a layer by itself off screen and then across the screen.  It wasn't working and told me about trying to do something with a nil value.  I did a bunch of ctrl-z to undo all the nonsense I had done and then I went to far so I quickly did a bunch of ctrl-y while everything was still up.  It made a selection of the sprite and then crashed.  Anyway, i didn't wanna just leave a comment on the itch page because generally speaking i think this is more of a PEBKAC problem than anything else.  Thanks for writing it though!  Despite my best efforts I do find it useful.

Windows 10, Aseprite 1.2.40 x64.  Canvas size of about 270x480 (I'm making reels for Instagram lol)

Anyway, thanks!!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots / a link to a video or a gif to help explain the issue encountered. This helps ALOT in debugging and fixing issues much faster.

**System Information (please complete the following information):**
 - Operating System: [e.g. Windows 10, Linux, iOS]
 - Aseprite Version: [e.g 1.2.22, 1.3-beta18]
 - Tool + Tool Version: [e.g Carbs Toolbar v3.0.0]
 - Size of Canvas (Width x Height): [e.g 480 x 360]

**Additional context**

**Comment by CarbsCode** [comment]
@natesturdevant Thanks for writing this up!

Unfortunately undoing and redoing alot of actions (espcially ones with alot of calculations in them) can cause Aseprite to crash. Generally speaking if an error happens its almost better to just close the document and reopen because it happened mid way though when it ran in to the issue.

Now that a being said you should be able to tween off and back on the canvas in the latest update. 

Which version of the tool are you currently using?

I see that you typed above the template where all the questions are asked is there any chance you would be able to fill in any of those details? I can def try and help you out getting the tool to work the way your wanting. 

I will say the tool IS for creating motion and color tweens as it would be far too complicated to do shape tweens like I flash for instance going from one shape to another. It just couldn't be done here as these are pixels and not vector graphics 😀

I do plan to put out a quick how to video on usage of each tool I have but time is always a battle!

**Comment by natesturdevant** [comment]
Thanks for the quick reply!  That's definitely the problem then.  I think I was expecting too much from it.  Generally speaking I think it's pretty intuitive but yeah a video would be helpful.  Maybe include a note in there about how you shouldn't bang out a bunch of ctrl-zs and ys lol.  Or maybe you did and I just didn't read it.  Anyway, I have gotten a lot of good use out of it and being able to do position and rotation at once is pretty great.  The program I use to assemble everything also does similar tweening but I find that I prefer to use the Tween Machine after a bit of practice.  

I'm using 1.1 and I did go back in the same .aseprite file and banged out a bunch of undos and redos and didn't manage to crash it again.  I'll just be more careful in the future.  I think that was the real problem here.  Pixel manipulation != simple after all.  Thanks again for you attention in the matter.

**Comment by CarbsCode** [comment]
Absolutely! And yeah a video is going to be much more helpful.

Not sure if this helps but here is the example I made showing how to tween outside the original canvas.  It works by giving it extra room and still alloying the tool to "See" your sprite but then you crop it back down to the original canvas size once your done all of your tweens :)


https://github.com/CarbsCode/CarbsAsepriteExtensions/assets/53490199/4bb5ffe6-e761-4094-a310-d73023c98583

Let me know if this helps! Also if this is what your trying to do :) Again thank you for posting!

**Comment by natesturdevant** [comment]
Yes, I've started letting the Tween Machine expand the canvas rather than trying to do so myself which is helpful.  It's working fine; I was mostly worried about the crashing but I think just using the tool smarter will alleviate that.  It's working great for me anyway.  Thanks so much for your help!
